### ISSUE TITLE
Media should sync on media library changes

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy#124]
It was strange to me to install the software and have to go manually do a sync to show my media.

What do you think about automatically running a sync on boot, optionally perhaps if there are no songs or something?

**Comment by aidewoode** [comment]
Do you mean automatically sync after the service is running? I don't think it's necessary. If user don't use docker to run black candy, there is no way to setup media sync task after service running. For user the first time manually sync it's not a problem. 

I think a more useful similar feature would be to listen for media library changes and then automatically sync it.

**Comment by jaredmoody** [comment]
It was strange to me to set up black candy with my media directory and then not see any media, that experience is what I'm proposing improving, my first thought was just queue a sync job whenever the app server boots - but listening for library changes would be even better I think as it would address what I was experiencing and improve the experience of adding new media.

**Comment by jaredmoody** [comment]
Perhaps the [listen gem](https://github.com/guard/listen) would be a good candidate - we could start a process with rake that listens for file additions/deletions/changes and syncs the media?

I'm not too familiar with Docker, would it be possible to run more than one process inside the worker container perhaps?
