### ISSUE TITLE
Add to Current playlist

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy#152]
As far as I can tell there isn't a way to add a song to the end of the Current list without stopping what's currently playing, nor a way to add a song to play next in the Current list.

What do you think about adding those features? I'm happy to help with these as I would use them regularly.

**Comment by aidewoode** [comment]
I think it's great to have those features.

**Comment by jaredmoody** [comment]
Great - I'm not sure how you would like the UI to work - maybe we put a new icon where the Add to Playlist icon is and add a popup that has these options?

- Add to Playlist
- Play Next
- Add to Current

**Comment by aidewoode** [comment]
OK, just like you said add a dropdown menu and with these options

- Add to Playlist -> Select a custom playlist to add.
- Play Next -> Add song next to the currently playing song.
- Play Later -> Add song to the end of the current playlist.

**Comment by aidewoode** [comment]
OK, just like you said add a dropdown menu and with these options

- Add to Playlist -> Select a custom playlist to add.
- Play Next -> Add song next to the currently playing song.
- Play Later -> Add song to the end of the current playlist.
