### ISSUE TITLE
Error response from daemon: Conflict. The container name "/blackcandy_app" is already in use by container XXX

### ISSUE THREAD

**Issue by EgonHeuson** [blackcandy-org/black_candy#180]
Hello,
I used the docker-compose.yml file as indicated but when executing the command $ docker-compose up -d I get the following error. Any idea? 

user@BlackCandy:/home/user/blackcandy# docker compose up -d
[+] Running 32/32
 ⠿ postgres Pulled                                                                                   23.9s
   ⠿ 6c40cc604d8e Pull complete                                                                      10.0s
   ⠿ 3ea5fa93d025 Pull complete                                                                      10.6s
   ⠿ 146f5c88cacb Pull complete                                                                      11.0s
   ⠿ 1549d653d730 Pull complete                                                                      17.6s
   ⠿ 1f52f9ddebb6 Pull complete                                                                      18.0s
   ⠿ a4c85e4b61b7 Pull complete                                                                      18.2s
   ⠿ a562b26ea57a Pull complete                                                                      18.5s
   ⠿ 04f1f3b24313 Pull complete                                                                      18.9s
   ⠿ f2684c2bfb4b Pull complete                                                                      19.2s
 ⠿ redis Pulled                                                                                      15.6s
   ⠿ cbdbe7a5bc2a Pull complete                                                                       6.5s
   ⠿ dc0373118a0d Pull complete                                                                       7.0s
   ⠿ cfd369fe6256 Pull complete                                                                       8.3s
   ⠿ 152ffd6a3b24 Pull complete                                                                      10.0s
   ⠿ 7c01860f13a3 Pull complete                                                                      10.5s
   ⠿ aa6ecacd3bee Pull complete                                                                      10.9s
 ⠿ worker Pulled                                                                                     44.2s
 ⠿ web Pulled                                                                                        44.2s
 ⠿ listener Pulled                                                                                   44.2s
 ⠿ app Pulled                                                                                        44.2s
   ⠿ 2408cc74d12b Pull complete                                                                       1.3s
   ⠿ fdbd9a0f0a99 Pull complete                                                                       3.9s
   ⠿ 4af624e0dc7d Pull complete                                                                       4.2s
   ⠿ c013a669105b Pull complete                                                                      12.9s
   ⠿ 6f2847677b49 Pull complete                                                                      13.1s
   ⠿ d50ad5c2f0c0 Pull complete                                                                      33.6s
   ⠿ c550ed8f4549 Pull complete                                                                      33.8s
   ⠿ cd5789dc6f9d Pull complete                                                                      34.1s
   ⠿ c273974abcb6 Pull complete                                                                      39.3s
   ⠿ fb908f56be38 Pull complete                                                                      39.7s
   ⠿ f8702d6c0b32 Pull complete                                                                      39.9s
[+] Running 7/7
 ⠿ Network blackcandy_default                   Created                                               0.2s
 ⠿ Volume "blackcandy_production_uploads_data"  Crea...                                               0.0s
 ⠿ Volume "blackcandy_production_db_data"       Created                                               0.0s
 ⠿ Volume "blackcandy_production_redis_data"    Create...                                             0.0s
 ⠿ Container blackcandy_postgres                Created                                               2.4s
 ⠿ Container blackcandy_redis                   Created                                               2.4s
 ⠿ Container blackcandy_app                     Created                                               0.1s
Error response from daemon: Conflict. The container name "/blackcandy_app" is already in use by container "5e4af0acded20d7dfce8f4814d5f722a10425fd23e77df561d1f10c7f753dfb9". You have to remove (or rename) that container to be able to reuse that name.

**Comment by aidewoode** [comment]
Hi, The error message already told you the solution

> The container name "/blackcandy_app" is already in use by container "5e4af0acded20d7dfce8f4814d5f722a10425fd23e77df561d1f10c7f753dfb9". You have to remove (or rename) that container to be able to reuse that name.

So you can remove the duplicate container like this: `docker container rm 5e4af0acded20d7dfce8f4814d5f722a10425fd23e77df561d1f10c7f753dfb9`. Then you can try to start the those services `docker-compose up -d`

**Comment by EgonHeuson** [comment]
Hello,
Thanks for the answer but I got this problem when using the `docker-compose up -d` command from scratch. So I didn't have any container when it started...

**Comment by aidewoode** [comment]
Sorry, I didn't notice this is the issue from scratch. And I have done some test on virtual machine. This error only occurred when I use docker-compose v2.  But on docker-compose v1, all things were fine. I think this issue relate to this docker-compose issue https://github.com/docker/compose/issues/9014 . 

So for now you should use  docker-compose v1 instead of docker-compose v2. And I will take some time to find out how to support docker-compose v2 and fix this issue.

**Comment by EgonHeuson** [comment]
Dear Aidewoode,
No problem. Ok great to know! I'll check this :-) Have a nice day!!
