### ISSUE TITLE
Requirements for how audio library is stored

### ISSUE THREAD

**Issue by sruckh** [blackcandy-org/black_candy#273]
My music library is stored like this:

  <Album_Name>
               |
               -- <track>. <artist> - <song_title>.mp3

In the docker compose file I have /storage/myaudiolibrary:/media_data in both the nginx-proxy and app section of the configuration file.

Nothing shows up when logging into the server.

Is there a requirement for how the audio Library needs to be laid out?

**Comment by aidewoode** [comment]
Have you synced the library in the setting page?

**Comment by sruckh** [comment]
I better go back and look at the documentation to see if I missed that step.  Yes, sync'ing the library made items appear in the library.  Thank You.
