### ISSUE TITLE
Media path can't be blank

### ISSUE THREAD

**Issue by pkawalya** [blackcandy-org/black_candy#334]
Puma starting in single mode...
13:36:23 web.1  | * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
13:36:23 web.1  | *  Min threads: 5
13:36:23 web.1  | *  Max threads: 5
13:36:23 web.1  | *  Environment: development
13:36:23 web.1  | *          PID: 19372
13:36:23 web.1  | * Listening on http://127.0.0.1:3000
13:36:23 web.1  | * Listening on http://[::1]:3000
13:36:23 web.1  | Use Ctrl-C to stop
13:36:24 web.1  |   Setting Load (0.3ms)  SELECT "settings".* FROM "settings" ORDER BY "settings"."id" ASC LIMIT $1  [["LIMIT", 1]]
13:36:24 web.1  |   ↳ app/models/concerns/global_setting_concern.rb:16:in `instance'
13:36:24 web.1  | Exiting
13:36:24 web.1  | /Users/pkawalya/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/validations.rb:84:in `raise_validation_error': Validation failed: Media path can't be blank (ActiveRecord::RecordInvalid)

**Comment by aidewoode** [comment]
Hi, thanks for reporting this issue. I have fixed this issue in https://github.com/blackcandy-org/black_candy/pull/335. You can try the latest docker image of edge version to see if the issue is fixed.

**Comment by pkawalya** [comment]
Much appreciated. Thank you
