### ISSUE TITLE
Trying to look for where to upload from

### ISSUE THREAD

**Issue by pkawalya** [blackcandy-org/black_candy#342]
Kindly help with where one can upload from. Thank you for the great work

**Comment by aidewoode** [comment]
Hi, thanks for trying Black Candy. Black Candy doesn't support direct music file upload yet. You can only set the media_path in the settings page, then sync  
all music inside the directory.  If you use docker image of Black Candy, don't forget to mount the directory from host to docker container, then set the media_path to the directory you mounted to. You can see more detail in [README](https://github.com/blackcandy-org/black_candy#media-files-mounts)

**Comment by piscespieces** [comment]
Hey @pkawalya 

I'm running Black Candy in development with no Docker setup.

Head over to Settings > Media path, in the text box input an absolute path to a local directory from your computer that has audio files in it, then hit **save**, and then the **Sync** button. At this point you should be able to see music in your Home
