### ISSUE TITLE
App

### ISSUE THREAD

**Issue by gonjat** [blackcandy-org/black_candy#46]
Will there be an android app?

**Comment by aidewoode** [comment]
No, I don't have a plan to write mobile app for black_candy yet. Cause black_candy use responsive design, So it will work fine on mobile browser.

**Comment by gonjat** [comment]
Oh OK thanks. I will use waveline in the mean time.  Yours looks very nice. I will try it when or if there is an app. Thanks.

**Comment by jaredmoody** [comment]
I'd be willing to help contribute towards a turbo-ios or trubo-android app, I've written these before.

**Comment by aidewoode** [comment]
@jaredmoody  
It would be great if you could develop mobile apps for black candy, I also have a plan to build mobile app for black candy this year. I can do some iOS development, so I can contribute to iOS app. If you want some help , please contact me. Thanks.

**Comment by jaredmoody** [comment]
@aidewoode great, do you want to create some repos (maybe black_candy_ios, black_candy_android) and either I'll send some PRs or add me as a contributor and I'll push some code?

**Comment by aidewoode** [comment]
@jaredmoody Hi, I created a new organization https://github.com/blackcandy-org, and created new repos for mobile app, I will invite you as a member

**Comment by aidewoode** [comment]
Hi, everyone. The iOS app of Black Candy is beta now. You can visit here https://testflight.apple.com/join/TwMUVmDl and join TestFlight to give it a try.

**Comment by aidewoode** [comment]
Hey, I have released the first beta version of Android app of Black Candy. You can download the APK to try it from here https://github.com/blackcandy-org/black_candy_android/releases/tag/v1.0.0.beta1. As all iOS and Android apps have been released the beta version. And the first stable version of mobile apps will coming with Black Candy 3.0 soon. I am going to close this issue.
